# Generated by Django 3.0.8 on 2020-07-24 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylab', '0002_auto_20200715_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='diary', max_length=40),
        ),
    ]
