# Generated by Django 3.0.8 on 2020-10-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylab', '0003_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='modify_date',
            field=models.DateTimeField(null=True),
        ),
    ]
